name: "build-latest"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - "src/Dockerfile"
  pull_request:
    branches:
      - "main"
      - "master"
    paths:
      - "src/**"

jobs:
  docker_buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Perform setup steps
        uses: JonasAlfredsson/checkout-qemu-buildx@v2
        with:
          should_login: ${{ github.event_name != 'pull_request' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version numbers from the Dockerfile
        id: tagger
        run: bash .github/version_extractor.sh src/Dockerfile >> $GITHUB_ENV

      - name: Build and push all images
        uses: docker/build-push-action@v3
        with:
          context: ./src
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
          pull: true
          no-cache: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            jonasal/network-tools:latest
            jonasal/network-tools:${{ env.VERSION_MAJOR }}
            jonasal/network-tools:${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}
